name: asmaul_husna
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.2
  path: ^1.8.0
  flutter_svg: ^2.0.10+1
  audioplayers: ^6.1.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^1.1.1
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/ic_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/images/
    - assets/sounds/asmaul_husna/
    - assets/sounds/hijaiyah/
    - assets/splash_screen.png
